# Sponsorship options for lightspeedwp
github: [lightspeedwp]
# Only GitHub sponsorship is currently active for the lightspeedwp organization.
# To add other platforms, update this file and documentation accordingly.
