# Sponsorship options for lightspeedwp

github: [lightspeedwp]

custom:
  # Company
  - ["https://lightspeedwp.agency/", "LightSpeed Agency Home"]
  - ["https://lightspeedwp.agency/blog/", "LightSpeed Blog"]
  - ["https://lightspeedwp.agency/contact/", "LightSpeed Contact"]

  # LSX Design System
  - ["https://lsx.design/", "LSX Design System Home"]
  - ["https://figma.com/community/file/1253721166417292990/lsx-design-for-wordpress-woocommerce", "LSX Design on Figma"]
  - ["http://wordpress.org/themes/lsx-design", "LSX Design WordPress Theme"]
  - ["https://github.com/lightspeedwp/lsx-design", "LSX Design GitHub Repo"]

  # Tour Operator Plugin
  - ["https://touroperator.solutions/", "Tour Operator Solutions"]
  - ["https://figma.com/community/file/1397897183253228355", "Tour Operator Figma Design"]
  - ["http://wordpress.org/plugins/tour-operator", "Tour Operator WordPress Plugin"]
  - ["https://github.com/lightspeedwp/tour-operator", "Tour Operator GitHub Repo"]
  - ["https://www.wetu.com", "Sponsored by Wetu"]

# Note: 
# - The custom field supports either a string URL, or a two-item array [URL, label/domain] per the GitHub documentation.