pull_request_rules:
  - name: Keep Dependabot dependency updates on develop current
    conditions:
      - author~=^(dependabot\[bot\]|app/dependabot)$
      - base=develop
      - label=area:dependencies
      - -draft
      - -conflict
      - "#commits-behind > 0"
    actions:
      update:

  - name: Auto-merge Dependabot dependency updates on develop
    conditions:
      - author~=^(dependabot\[bot\]|app/dependabot)$
      - base=develop
      - label=area:dependencies
      - -label=meta:dependabot-security
      - check-success=All Checks Passed
      - -draft
      - -conflict
    actions:
      merge:
        method: squash

  - name: Auto-merge Dependabot security updates on develop
    conditions:
      - author~=^(dependabot\[bot\]|app/dependabot)$
      - base=develop
      - label=area:dependencies
      - label=meta:dependabot-security
      - check-success=All Checks Passed
      - -draft
      - -conflict
    actions:
      merge:
        method: squash
