pull_request_rules:
  - name: Auto-merge Dependabot dependency updates on develop
    conditions:
      - author~=^(dependabot\[bot\]|app/dependabot)$
      - base=develop
      - label=area:dependencies
      - -label=meta:dependabot-security
      - check-success=CI / check
      - check-success=CI / lint
      - check-success=changelog-validate / validate
      - -draft
      - -conflict
    actions:
      merge:
        method: squash

  - name: Auto-merge Dependabot security updates on develop
    conditions:
      - author~=^(dependabot\[bot\]|app/dependabot)$
      - base=develop
      - label=area:dependencies
      - label=meta:dependabot-security
      - check-success=CI / check
      - check-success=CI / lint
      - check-success=changelog-validate / validate
      - -draft
      - -conflict
    actions:
      merge:
        method: squash
