let buildLabelingReport;

beforeAll(async () => {
  ({ buildLabelingReport } = await import("../label-reporting.js"));
});

// TODO: This test suite may fail due to polluted global state from label-sync.test.js
// Fix label-sync global mock cleanup first (see TODO in label-sync.test.js), then re-validate
// Error manifests as: "Failed to standardize labels: Critical system error"
describe("buildLabelingReport", () => {
  it("generates a markdown report for labels", () => {
    const report = buildLabelingReport({
      added: ["status:needs-review", "type:feature"],
      removed: ["type:bug"],
      migrated: [{ from: "priority:low", to: "priority:high" }],
      rulesApplied: ["rule:sync-labels"],
      errors: ["Example error"],
    });

    expect(report).toContain("## 🏷️ Label Actions Report");
    expect(report).toContain("**Total Changes:** 4");
    expect(report).toContain("### ➕ Added Labels (2)");
    expect(report).toContain("`status:needs-review`");
    expect(report).toContain("### ➖ Removed Labels (1)");
    expect(report).toContain("`type:bug`");
    expect(report).toContain("### 🔄 Migrated Labels (1)");
    expect(report).toContain("`priority:low` → `priority:high`");
    expect(report).toContain("### 📋 Rules Applied");
    expect(report).toContain("rule:sync-labels");
    expect(report).toContain("### ⚠️ Errors (1)");
    expect(report).toContain("Example error");
    expect(report).toContain("_Generated by LightSpeedWP Labeling Agent_");
  });
});
