#!/usr/bin/env node

/**
 * Generate weekly metrics summary report
 *
 * Creates markdown report from aggregated metrics and writes to:
 * - .github/reports/metrics/weekly-summary-latest.md (current week)
 * - .github/reports/metrics/weekly/weekly-summary-YYYY-WXX.md (archive)
 */

const fs = require('fs');
const path = require('path');

const REPORTS_DIR = process.env.REPORTS_DIR || '.github/reports/metrics';
const REPORT_DATE = process.env.REPORT_DATE || new Date().toISOString().split('T')[0];
const METRICS_JSON = process.env.METRICS_JSON || '{}';

try {
  // Ensure reports directory exists
  if (!fs.existsSync(REPORTS_DIR)) {
    fs.mkdirSync(REPORTS_DIR, { recursive: true });
  }

  let metrics = {};
  try {
    metrics = JSON.parse(METRICS_JSON);
  } catch (err) {
    console.warn(`⚠️  Could not parse metrics JSON: ${err.message}`);
  }

  // Generate report markdown
  const report = generateReport(metrics, REPORT_DATE);

  // Write current week report
  const currentFile = path.join(REPORTS_DIR, 'weekly-summary-latest.md');
  fs.writeFileSync(currentFile, report, 'utf8');

  console.log(`✅ Generated report: ${currentFile}`);
  console.log(`   Date: ${REPORT_DATE}`);
  console.log(`   Size: ${report.length} characters`);

  // Also write versioned report for archive
  const week = getWeekNumber(new Date(REPORT_DATE));
  const archiveDir = path.join(REPORTS_DIR, 'weekly');
  if (!fs.existsSync(archiveDir)) {
    fs.mkdirSync(archiveDir, { recursive: true });
  }
  const archiveFile = path.join(archiveDir, `weekly-summary-${week}.md`);
  fs.writeFileSync(archiveFile, report, 'utf8');
} catch (err) {
  console.error(`❌ Error generating report: ${err.message}`);
  process.exit(1);
}

/**
 * Generate markdown report from metrics
 */
function generateReport(metrics, reportDate) {
  const week = getWeekNumber(new Date(reportDate));
  const title = `# Weekly Metrics Summary — ${reportDate}`;
  const subtitle = `**Week:** ${week} | **Generated:** ${new Date().toISOString()}`;

  const sections = [];
  sections.push(title);
  sections.push('');
  sections.push(subtitle);
  sections.push('');

  // Git Activity Section
  if (metrics.summary?.gitActivity) {
    const { commitsLast7Days, uniqueAuthorsLast7Days, period } = metrics.summary.gitActivity;
    sections.push('## 📊 Git Activity');
    sections.push('');
    sections.push(`- **Commits:** ${commitsLast7Days}`);
    sections.push(`- **Unique Authors:** ${uniqueAuthorsLast7Days}`);
    sections.push(`- **Period:** ${period}`);
    sections.push('');
  }

  // Meta Metrics Section
  if (metrics.summary?.meta) {
    const { coverage, changes, errors, optouts } = metrics.summary.meta;
    sections.push('## 🏷️ Meta Metrics (Frontmatter, Badges, Footers)');
    sections.push('');
    sections.push(`- **Coverage:** ${coverage || 'N/A'}%`);
    sections.push(`- **Changes:** ${changes || 0}`);
    sections.push(`- **Errors:** ${errors || 0}`);
    sections.push(`- **Opt-outs:** ${optouts || 0}`);
    sections.push('');
  }

  // Workflow Health Section
  sections.push('## ⚙️ Workflow Health');
  sections.push('');
  sections.push('| Metric | Value | Status |');
  sections.push('| --- | --- | --- |');
  sections.push('| Lint Checks | Running | ✅ |');
  sections.push('| Test Coverage | Monitored | ✅ |');
  sections.push('| Schema Validation | Active | ✅ |');
  sections.push('');

  // Summary Statistics
  sections.push('## 📈 Summary');
  sections.push('');
  sections.push('This week\'s metrics snapshot provides visibility into repository health, activity, and automation effectiveness.');
  sections.push('');
  sections.push('### Key Insights');
  sections.push('');
  if (metrics.summary?.gitActivity?.commitsLast7Days > 10) {
    sections.push('- 🔥 **High activity:** Significant development velocity');
  } else if (metrics.summary?.gitActivity?.commitsLast7Days > 0) {
    sections.push('- ⚙️ **Moderate activity:** Ongoing maintenance and improvements');
  } else {
    sections.push('- 📭 **Low activity:** Minimal changes this week');
  }
  sections.push('');

  // Footer
  sections.push('---');
  sections.push('');
  sections.push('### View More');
  sections.push('');
  sections.push('- [Metrics Directory](./)');
  sections.push('- [Historical Weekly Reports](./weekly/)');
  sections.push('- [Workflow Reports](../workflows/)');
  sections.push('');
  sections.push('*Report generated by metrics-summary workflow.*');

  return sections.join('\n');
}

/**
 * Get ISO week number (YYYY-Www format)
 */
function getWeekNumber(date) {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + 4 - (d.getDay() || 7));
  const yearStart = new Date(d.getFullYear(), 0, 1);
  const weekNumber = Math.ceil(((d - yearStart) / 86400000 + 1) / 7);
  return `${d.getFullYear()}-W${String(weekNumber).padStart(2, '0')}`;
}
