/**
 * planner.agent.js
 *
 * Generates and posts execution plans for PRs and issues.
 * Analyzes context (title, description, labels, linked issues) and generates
 * structured checklists for different plan types (architecture, implementation, task).
 * @module scripts/agents/planner.agent.js
 * @see agents/task-planner.agent.md
 */

import path from "path";
import { fileURLToPath, pathToFileURL } from "url";
import * as core from "@actions/core";
import * as github from "@actions/github";
import { Logger } from "../utils/logger.js";

const logger = new Logger(process.env.LOG_LEVEL || "info");

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function log(message) {
  const timestamp = new Date().toISOString();
  console.log(`[planner] ${timestamp} ${message}`);
}

function extractLinkedIssues(text) {
  if (!text) return [];
  const issuePattern = /#(\d+)/g;
  const matches = text.match(issuePattern) || [];
  return matches.map((m) => m.slice(1));
}

function determinePlanType(title, labels, description) {
  const text = `${title} ${description || ""}`.toLowerCase();
  if (
    labels.includes("type:architecture") ||
    text.includes("design") ||
    text.includes("architecture")
  ) {
    return "architecture";
  }
  if (
    labels.includes("type:feature") ||
    labels.includes("type:enhancement") ||
    text.includes("implement")
  ) {
    return "implementation";
  }
  return "task";
}

function generateArchitecturePlan(issue) {
  return `## 📐 Architecture Plan for #${issue.number}

### Phase 1: Design Review
- [ ] Review requirements and acceptance criteria
- [ ] Identify constraints and dependencies
- [ ] Document assumptions
- [ ] Create architecture diagram (if needed)

### Phase 2: API Contract
- [ ] Define interfaces and contracts
- [ ] Document method signatures
- [ ] Specify error handling strategy
- [ ] Review with team

### Phase 3: Data Model
- [ ] Define entity relationships
- [ ] Document data flow
- [ ] Identify persistence requirements
- [ ] Plan migrations (if applicable)

### Phase 4: Implementation
- [ ] Break down into tasks
- [ ] Assign ownership
- [ ] Set timelines
- [ ] Plan reviews and testing

---
**Generated by Planner Agent** <!-- planner-agent-summary -->`;
}

function generateImplementationPlan(issue) {
  return `## 🔨 Implementation Plan for #${issue.number}

### Phase 1: Setup
- [ ] Create feature branch
- [ ] Set up development environment
- [ ] Review related code and documentation
- [ ] Identify dependencies

### Phase 2: Core Implementation
- [ ] Implement core logic
- [ ] Add error handling
- [ ] Write inline documentation
- [ ] Self-review code

### Phase 3: Testing
- [ ] Write unit tests
- [ ] Write integration tests
- [ ] Test error cases
- [ ] Achieve target coverage (≥80%)

### Phase 4: Documentation
- [ ] Update README if needed
- [ ] Add code comments for complex logic
- [ ] Document new APIs
- [ ] Update CHANGELOG.md

### Phase 5: Review & Polish
- [ ] Address code review feedback
- [ ] Performance testing if applicable
- [ ] Final validation
- [ ] Prepare for merge

---
**Generated by Planner Agent** <!-- planner-agent-summary -->`;
}

function generateTaskPlan(issue) {
  return `## ✅ Task Plan for #${issue.number}

### Phase 1: Analysis
- [ ] Understand requirements
- [ ] Break down into subtasks
- [ ] Identify dependencies
- [ ] Estimate effort

### Phase 2: Research
- [ ] Review existing solutions
- [ ] Document findings
- [ ] Identify tools/libraries needed
- [ ] Plan implementation approach

### Phase 3: Implementation
- [ ] Execute plan
- [ ] Test thoroughly
- [ ] Document decisions
- [ ] Create supporting artifacts

### Phase 4: Verification
- [ ] Validate against requirements
- [ ] Peer review
- [ ] Final quality check
- [ ] Close related issues

---
**Generated by Planner Agent** <!-- planner-agent-summary -->`;
}

async function analyzeContext(octokit, context) {
  const issue = context.payload.issue || context.payload.pull_request;
  if (!issue) {
    throw new Error("No issue or PR found in context");
  }

  const title = issue.title || "";
  const description = issue.body || "";
  const linkedIssues = extractLinkedIssues(description);

  let labels = [];
  try {
    const issueData = await octokit.rest.issues.get({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
    });
    labels = issueData.data.labels.map((l) => l.name);
  } catch (error) {
    core.warning(`Could not fetch issue labels: ${error.message}`);
  }

  return {
    number: issue.number,
    title,
    description,
    labels,
    linkedIssues,
    type: determinePlanType(title, labels, description),
  };
}

function generatePlan(context) {
  switch (context.type) {
    case "architecture":
      return generateArchitecturePlan({ number: context.number });
    case "implementation":
      return generateImplementationPlan({ number: context.number });
    default:
      return generateTaskPlan({ number: context.number });
  }
}

async function run(context = github.context, options = {}) {
  const startTime = Date.now();
  try {
    const token = core.getInput("github-token") || process.env.GITHUB_TOKEN;
    if (!token) {
      throw new Error(
        "Missing GITHUB_TOKEN: provide via 'github-token' input or GITHUB_TOKEN env var",
      );
    }

    logger.info("Planner agent started", {
      event: "start",
      issueNumber:
        context.payload.issue?.number || context.payload.pull_request?.number,
      repo: context.repo.repo,
    });

    const dryRun =
      options.dryRun !== undefined
        ? options.dryRun
        : process.argv.includes("--dry-run") || process.env.DRY_RUN === "true";

    let octokit;
    try {
      octokit = github.getOctokit(token);
    } catch (error) {
      throw new Error(`Failed to initialize GitHub client: ${error.message}`);
    }

    const issue = context.payload.issue || context.payload.pull_request;
    if (!issue) {
      core.info("No PR or issue in context; exiting.");
      return;
    }

    const analysisContext = await analyzeContext(octokit, context);
    const plan = generatePlan(analysisContext);

    logger.info("Plan generated", {
      event: "plan-generated",
      planType: analysisContext.type,
      issueNumber: analysisContext.number,
    });

    if (dryRun) {
      core.info(`DRY-RUN: Would post plan:\n${plan}`);
      logger.info("Dry-run mode: plan not posted", { event: "dry-run" });
    } else {
      try {
        const prComments = await octokit.rest.issues.listComments({
          owner: context.repo.owner,
          repo: context.repo.repo,
          issue_number: issue.number,
        });

        const existingComment = prComments.data.find((c) =>
          c.body?.includes("<!-- planner-agent-summary -->"),
        );

        if (existingComment) {
          await octokit.rest.issues.updateComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: existingComment.id,
            body: plan,
          });
          core.info("Planner comment updated.");
          logger.info("Comment updated successfully", {
            event: "comment-updated",
            issueNumber: issue.number,
            commentId: existingComment.id,
          });
        } else {
          await octokit.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue.number,
            body: plan,
          });
          core.info("Planner comment posted.");
          logger.info("Comment posted successfully", {
            event: "comment-created",
            issueNumber: issue.number,
          });
        }
      } catch (error) {
        throw new Error(
          `Failed to post plan on #${issue.number}: ${error.message}`,
        );
      }
    }
    logger.info("Planner agent completed successfully", {
      event: "complete",
      duration: Date.now() - startTime,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    logger.error("Planner agent failed", {
      event: "error",
      error: message,
      duration: Date.now() - startTime,
    });
    core.setFailed(message);
    process.exit(1);
  }
}

async function runPlanner(options = {}) {
  const { dryRun = true } = options;

  try {
    const token = process.env.GITHUB_TOKEN;
    if (!token && !dryRun) {
      throw new Error(
        "Missing GITHUB_TOKEN environment variable (required for write operations)",
      );
    }

    const eventName = process.env.GITHUB_EVENT_NAME || "local";
    const repoRoot = path.resolve(__dirname, "..", "..");

    log(`Starting planner agent (${dryRun ? "dry-run" : "apply"})`);
    log(`Context: event=${eventName}, repoRoot=${repoRoot}`);

    if (!dryRun) {
      log("Planner stub mode: implement custom automation as needed.");
    }

    log("Planner agent finished without errors.");
  } catch (error) {
    console.error(`[planner] fatal error: ${error.message}`);
    process.exit(1);
  }
}

export { run, runPlanner };

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  const dryRun = !process.argv.includes("--apply");
  run(github.context, { dryRun }).catch((error) => {
    console.error("[planner] fatal error", error);
    process.exit(1);
  });
}
