/**
 * planner.agent.js
 *
 * Generates and posts execution plans for PRs and issues.
 * Analyzes context (title, description, labels, linked issues) and generates
 * structured checklists for different plan types (architecture, implementation, task).
 * @module scripts/agents/planner.agent.js
 * @see agents/task-planner.agent.md
 */

import path from "path";
import * as core from "@actions/core";
import * as github from "@actions/github";
import { Logger } from "../utils/logger.js";

const logger = new Logger(process.env.LOG_LEVEL || "info");

function log(message) {
  const timestamp = new Date().toISOString();
  console.log(`[planner] ${timestamp} ${message}`);
}

function extractLinkedIssues(text) {
  if (!text) return [];
  const issuePattern = /#(\d+)/g;
  const matches = text.match(issuePattern) || [];
  return matches.map((m) => m.slice(1));
}

function determinePlanType(title, labels, description) {
  const text = `${title} ${description || ""}`.toLowerCase();
  if (
    labels.includes("type:architecture") ||
    text.includes("design") ||
    text.includes("architecture")
  ) {
    return "architecture";
  }
  if (
    labels.includes("type:feature") ||
    labels.includes("type:enhancement") ||
    text.includes("implement")
  ) {
    return "implementation";
  }
  return "task";
}

function deriveProjectFromLabels(labels) {
  if (!Array.isArray(labels)) {
    return {
      project: null,
      confidence: "low",
      reason: "No clear project mapping; manual review recommended",
    };
  }

  // Map area labels to project names
  const areaToProject = {
    "area:workflows": "workflows-automation",
    "area:documentation": "documentation",
    "area:testing": "testing-coverage",
    "area:security": "security-hardening",
  };

  for (const label of labels) {
    if (areaToProject[label]) {
      return {
        project: areaToProject[label],
        confidence: "high",
        reason: `Derived from label '${label}'`,
      };
    }
  }

  // Check for type labels to suggest generic projects
  if (labels.includes("type:feature") || labels.includes("type:enhancement")) {
    return {
      project: "feature-development",
      confidence: "medium",
      reason: "Feature/enhancement type; recommend feature-development project",
    };
  }

  if (labels.includes("type:bug")) {
    return {
      project: "bug-fixes",
      confidence: "medium",
      reason: "Bug type; recommend bug-fixes project",
    };
  }

  return {
    project: null,
    confidence: "low",
    reason: "No clear project mapping; manual review recommended",
  };
}

function generateArchitecturePlan(issue) {
  return `## 📐 Architecture Plan for #${issue.number}

### Phase 1: Design Review
- [ ] Review requirements and acceptance criteria
- [ ] Identify constraints and dependencies
- [ ] Document assumptions
- [ ] Create architecture diagram (if needed)

### Phase 2: API Contract
- [ ] Define interfaces and contracts
- [ ] Document method signatures
- [ ] Specify error handling strategy
- [ ] Review with team

### Phase 3: Data Model
- [ ] Define entity relationships
- [ ] Document data flow
- [ ] Identify persistence requirements
- [ ] Plan migrations (if applicable)

### Phase 4: Implementation
- [ ] Break down into tasks
- [ ] Assign ownership
- [ ] Set timelines
- [ ] Plan reviews and testing

---
**Generated by Planner Agent** <!-- planner-agent-summary -->`;
}

function generateImplementationPlan(issue) {
  return `## 🔨 Implementation Plan for #${issue.number}

### Phase 1: Setup
- [ ] Create feature branch
- [ ] Set up development environment
- [ ] Review related code and documentation
- [ ] Identify dependencies

### Phase 2: Core Implementation
- [ ] Implement core logic
- [ ] Add error handling
- [ ] Write inline documentation
- [ ] Self-review code

### Phase 3: Testing
- [ ] Write unit tests
- [ ] Write integration tests
- [ ] Test error cases
- [ ] Achieve target coverage (≥80%)

### Phase 4: Documentation
- [ ] Update README if needed
- [ ] Add code comments for complex logic
- [ ] Document new APIs
- [ ] Update CHANGELOG.md

### Phase 5: Review & Polish
- [ ] Address code review feedback
- [ ] Performance testing if applicable
- [ ] Final validation
- [ ] Prepare for merge

---
**Generated by Planner Agent** <!-- planner-agent-summary -->`;
}

function generateTaskPlan(issue) {
  return `## ✅ Task Plan for #${issue.number}

### Phase 1: Analysis
- [ ] Understand requirements
- [ ] Break down into subtasks
- [ ] Identify dependencies
- [ ] Estimate effort

### Phase 2: Research
- [ ] Review existing solutions
- [ ] Document findings
- [ ] Identify tools/libraries needed
- [ ] Plan implementation approach

### Phase 3: Implementation
- [ ] Execute plan
- [ ] Test thoroughly
- [ ] Document decisions
- [ ] Create supporting artifacts

### Phase 4: Verification
- [ ] Validate against requirements
- [ ] Peer review
- [ ] Final quality check
- [ ] Close related issues

---
**Generated by Planner Agent** <!-- planner-agent-summary -->`;
}

async function analyzeContext(octokit, context) {
  const issue = context.payload.issue || context.payload.pull_request;
  if (!issue) {
    throw new Error("No issue or PR found in context");
  }

  const title = issue.title || "";
  const description = issue.body || "";
  const linkedIssues = extractLinkedIssues(description);

  let labels = [];
  try {
    const issueData = await octokit.rest.issues.get({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: issue.number,
    });
    labels = issueData.data.labels.map((l) => l.name);
  } catch (error) {
    core.warning(`Could not fetch issue labels: ${error.message}`);
  }

  return {
    number: issue.number,
    title,
    description,
    labels,
    linkedIssues,
    type: determinePlanType(title, labels, description),
    projectAssignment: deriveProjectFromLabels(labels),
  };
}

function generatePlan(context) {
  const baseIssue = { number: context.number };
  let plan;

  switch (context.type) {
    case "architecture":
      plan = generateArchitecturePlan(baseIssue);
      break;
    case "implementation":
      plan = generateImplementationPlan(baseIssue);
      break;
    default:
      plan = generateTaskPlan(baseIssue);
  }

  // Add project assignment recommendation if available
  if (context.projectAssignment?.project) {
    const projectSection = `
### 📋 Project Assignment

**Assigned Project:** \`${context.projectAssignment.project}\`
**Confidence:** ${context.projectAssignment.confidence}
**Reason:** ${context.projectAssignment.reason}
`;
    const marker = "<!-- planner-agent-summary -->";
    const markerIndex = plan.indexOf(marker);
    if (markerIndex !== -1) {
      const footerIndex = plan.lastIndexOf("---", markerIndex);
      if (footerIndex !== -1) {
        return (
          plan.slice(0, footerIndex) +
          projectSection.trimStart() +
          "\n" +
          plan.slice(footerIndex)
        );
      }
    }
  }

  return plan;
}

async function run(context = github.context, options = {}) {
  const startTime = Date.now();
  try {
    const token = core.getInput("github-token") || process.env.GITHUB_TOKEN;
    if (!token) {
      throw new Error(
        "Missing GITHUB_TOKEN: provide via 'github-token' input or GITHUB_TOKEN env var",
      );
    }

    logger.info("Planner agent started", {
      event: "start",
      issueNumber:
        context.payload?.issue?.number || context.payload?.pull_request?.number,
      repo: context.repo?.repo,
    });

    const dryRun =
      options.dryRun !== undefined
        ? options.dryRun
        : process.argv.includes("--dry-run") || process.env.DRY_RUN === "true";

    let octokit;
    try {
      octokit = github.getOctokit(token);
    } catch (error) {
      throw new Error(`Failed to initialize GitHub client: ${error.message}`, {
        cause: error,
      });
    }

    const issue = context.payload.issue || context.payload.pull_request;
    if (!issue) {
      core.info("No PR or issue in context; exiting.");
      return;
    }

    const analysisContext = await analyzeContext(octokit, context);
    const plan = generatePlan(analysisContext);

    logger.info("Plan generated", {
      event: "plan-generated",
      planType: analysisContext.type,
      issueNumber: analysisContext.number,
    });

    if (dryRun) {
      core.info(`DRY-RUN: Would post plan:\n${plan}`);
      logger.info("Dry-run mode: plan not posted", { event: "dry-run" });
      if (analysisContext.projectAssignment?.project) {
        core.info(
          `DRY-RUN: Would assign to project: ${analysisContext.projectAssignment.project} (${analysisContext.projectAssignment.confidence})`,
        );
      }
    } else {
      try {
        const prComments = await octokit.paginate(
          octokit.rest.issues.listComments,
          {
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue.number,
            per_page: 100,
          },
        );

        const existingComment = prComments.find((c) =>
          c.body?.includes("<!-- planner-agent-summary -->"),
        );

        if (existingComment) {
          await octokit.rest.issues.updateComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: existingComment.id,
            body: plan,
          });
          core.info("Planner comment updated.");
          logger.info("Comment updated successfully", {
            event: "comment-updated",
            issueNumber: issue.number,
            commentId: existingComment.id,
          });
        } else {
          await octokit.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue.number,
            body: plan,
          });
          core.info("Planner comment posted.");
          logger.info("Comment posted successfully", {
            event: "comment-created",
            issueNumber: issue.number,
          });
        }

        if (analysisContext.projectAssignment?.project) {
          core.info(
            `Project assignment: ${analysisContext.projectAssignment.project} (${analysisContext.projectAssignment.confidence})`,
          );
        }
      } catch (error) {
        throw new Error(
          `Failed to post plan on #${issue.number}: ${error.message}`,
          { cause: error },
        );
      }
    }
    logger.info("Planner agent completed successfully", {
      event: "complete",
      duration: Date.now() - startTime,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    logger.error("Planner agent failed", {
      event: "error",
      error: message,
      duration: Date.now() - startTime,
    });
    core.setFailed(message);
    process.exit(1);
  }
}

async function runPlanner(options = {}) {
  const { dryRun = true } = options;

  try {
    const token = process.env.GITHUB_TOKEN;
    if (!token && !dryRun) {
      throw new Error(
        "Missing GITHUB_TOKEN environment variable (required for write operations)",
      );
    }

    const eventName = process.env.GITHUB_EVENT_NAME || "local";
    const repoRoot = path.resolve(process.cwd());

    log(`Starting planner agent (${dryRun ? "dry-run" : "apply"})`);
    log(`Context: event=${eventName}, repoRoot=${repoRoot}`);

    if (!dryRun) {
      log("Planner stub mode: implement custom automation as needed.");
    }

    log("Planner agent finished without errors.");
  } catch (error) {
    console.error(`[planner] fatal error: ${error.message}`);
    process.exit(1);
  }
}

export { run, runPlanner };

if (process.argv[1] && /planner\.agent\.js$/.test(process.argv[1])) {
  const dryRun = !process.argv.includes("--apply");
  run(github.context, { dryRun }).catch((error) => {
    console.error("[planner] fatal error", error);
    process.exit(1);
  });
}
