/**
 * PR Comment Formatter
 * Formats validation results as GitHub PR comments
 */

/**
 * Format validation results as GitHub PR comment
 * @param {Object} validationResult - Validation results from validator
 * @returns {string} Markdown formatted comment
 */
function formatPRComment(validationResult = {}) {
  const {
    passed = 0,
    failed = 0,
    warnings = 0,
    entries = [],
    summary = "",
  } = validationResult;

  const total = passed + failed + warnings;
  const failurePercentage =
    total > 0 ? Math.round((failed / total) * 100) : 0;

  let comment = `## 📋 Changelog Quality Validation\n\n`;

  // Summary section
  comment += `### Summary\n\n`;
  comment += `| Status | Count | Percentage |\n`;
  comment += `|--------|-------|------------|\n`;
  comment += `| ✅ Passing | ${passed} | ${total > 0 ? Math.round((passed / total) * 100) : 0}% |\n`;
  comment += `| ⚠️ Warnings | ${warnings} | ${total > 0 ? Math.round((warnings / total) * 100) : 0}% |\n`;
  comment += `| ❌ Failing | ${failed} | ${failurePercentage}% |\n`;
  comment += `| 📝 Total | ${total} | 100% |\n\n`;

  // Status badge
  let statusEmoji = "✅";
  let statusText = "PASSED";

  if (failed > 0) {
    statusEmoji = "❌";
    statusText = "FAILED";
  } else if (warnings > 0) {
    statusEmoji = "⚠️";
    statusText = "CONDITIONAL PASS";
  }

  comment += `### Status\n\n`;
  comment += `${statusEmoji} **Validation ${statusText}**\n\n`;

  if (failed > 0) {
    comment += `All changelog entries must pass validation before merging. Please fix the issues below.\n\n`;
  } else if (warnings > 0) {
    comment += `All entries are valid, but ${warnings} warning(s) detected. Review and consider addressing them for better quality.\n\n`;
  } else {
    comment += `All entries meet quality standards. ✨\n\n`;
  }

  // Failed entries section (if any)
  if (failed > 0 && entries.length > 0) {
    const failedEntries = entries.filter(
      e => e.status === "failing" || e.status === "failed",
    );

    if (failedEntries.length > 0) {
      comment += `### ❌ Failing Entries\n\n`;
      comment += formatFailingEntriesTable(failedEntries);
      comment += `\n`;
    }
  }

  // Warning entries section (if any)
  if (warnings > 0 && entries.length > 0) {
    const warningEntries = entries.filter(e => e.status === "warning");

    if (warningEntries.length > 0) {
      comment += `### ⚠️ Entries with Warnings\n\n`;
      comment += formatWarningEntriesTable(warningEntries);
      comment += `\n`;
    }
  }

  // Remediation guidance
  if (failed > 0) {
    comment += `### 🔧 How to Fix\n\n`;
    comment += `1. Review the failing entries above\n`;
    comment += `2. Run validation locally:\n`;
    comment += `   \`\`\`bash\n`;
    comment += `   cd agents/changelog\n`;
    comment += `   npm run validate:changelog -- --json\n`;
    comment += `   \`\`\`\n`;
    comment += `3. Fix issues according to remediation guidance\n`;
    comment += `4. Push updates to continue validation\n\n`;
  }

  // Links to documentation
  comment += `### 📚 Learn More\n\n`;
  comment += `- [Changelog Quality Audit Guide](https://github.com/lightspeedwp/.github/blob/develop/docs/CHANGELOG_QUALITY_AUDIT.md)\n`;
  comment += `- [Validation Rules Reference](https://github.com/lightspeedwp/.github/blob/develop/docs/CHANGELOG_RULES.md)\n`;
  comment += `- [Changelog Format](https://keepachangelog.com/)\n\n`;

  // Footer
  comment += `---\n`;
  comment += `*Generated by [Changelog Quality Validator](https://github.com/lightspeedwp/.github/tree/develop/agents/changelog)*\n`;

  return comment;
}

/**
 * Format failing entries as table
 * @param {Array} entries - Failing entry objects
 * @returns {string} Markdown table
 */
function formatFailingEntriesTable(entries = []) {
  let table = `| Entry | Issues | Severity |\n`;
  table += `|-------|--------|----------|\n`;

  for (const entry of entries.slice(0, 10)) {
    const title = truncate(entry.title || "Untitled", 40);
    const issues = (entry.issues || []).map(i => `\`${i}\``).join(", ");
    const severity = entry.severity || "error";

    table += `| ${title} | ${issues || "Unknown"} | ${severity} |\n`;
  }

  if (entries.length > 10) {
    table += `| ... and ${entries.length - 10} more | ... | ... |\n`;
  }

  return table;
}

/**
 * Format warning entries as table
 * @param {Array} entries - Entry objects with warnings
 * @returns {string} Markdown table
 */
function formatWarningEntriesTable(entries = []) {
  let table = `| Entry | Warnings |\n`;
  table += `|-------|----------|\n`;

  for (const entry of entries.slice(0, 10)) {
    const title = truncate(entry.title || "Untitled", 40);
    const warnings = (entry.warnings || [])
      .map(w => `\`${w}\``)
      .join(", ");

    table += `| ${title} | ${warnings || "None"} |\n`;
  }

  if (entries.length > 10) {
    table += `| ... and ${entries.length - 10} more | ... |\n`;
  }

  return table;
}

/**
 * Format detailed remediation for single entry
 * @param {Object} entry - Entry object with issues
 * @returns {string} Markdown formatted remediation
 */
function formatEntryRemediation(entry = {}) {
  let text = `#### ${entry.title}\n\n`;

  text += `**Status**: `;
  if (entry.status === "failed" || entry.status === "failing") {
    text += `❌ Failing\n\n`;
  } else if (entry.status === "warning") {
    text += `⚠️ Warning\n\n`;
  } else {
    text += `✅ Passing\n\n`;
  }

  if (entry.issues && entry.issues.length > 0) {
    text += `**Issues**:\n`;
    for (const issue of entry.issues) {
      text += `- ${issue}\n`;
    }
    text += `\n`;
  }

  if (entry.remediation) {
    text += `**Remediation**:\n`;
    text += `${entry.remediation}\n\n`;
  }

  return text;
}

/**
 * Truncate text to max length with ellipsis
 * @param {string} text
 * @param {number} maxLength
 * @returns {string}
 */
function truncate(text, maxLength = 50) {
  if (text.length <= maxLength) {
    return text;
  }
  return text.substring(0, maxLength - 3) + "...";
}

/**
 * Create a compact one-line status comment
 * @param {Object} result - Validation result
 * @returns {string} Single-line status
 */
function formatCompactStatus(result = {}) {
  const { passed = 0, failed = 0, warnings = 0 } = result;

  if (failed > 0) {
    return `❌ Validation failed: ${failed} error(s), ${warnings} warning(s)`;
  } else if (warnings > 0) {
    return `⚠️ Validation conditional: ${passed} passed, ${warnings} warning(s)`;
  } else {
    return `✅ Validation passed: all ${passed} entries valid`;
  }
}

/**
 * Format results for PR status check description (max 140 chars)
 * @param {Object} result
 * @returns {string}
 */
function formatStatusCheckDescription(result = {}) {
  const { passed = 0, failed = 0, warnings = 0 } = result;

  const text =
    failed > 0
      ? `${failed} failing, ${warnings} warnings`
      : warnings > 0
        ? `${passed} passing, ${warnings} warnings`
        : `${passed} entries validated`;

  return text.substring(0, 140);
}

module.exports = {
  formatPRComment,
  formatFailingEntriesTable,
  formatWarningEntriesTable,
  formatEntryRemediation,
  formatCompactStatus,
  formatStatusCheckDescription,
  truncate,
};
