name: 'Label Pull Request Project'
on:
    pull_request_target:
        types: [opened, reopened, ready_for_review, review_requested, closed]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
    cancel-in-progress: true

permissions: {}

jobs:
    label_project:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/labeler@v3
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  configuration-path: .github/project-pr-labeler.yml
